# Generated by Django 4.0.10 on 2024-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_remove_article_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_to_read',
        ),
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
