# Generated by Django 4.0.10 on 2024-01-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_question_time_to_read_article_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(blank=True, default='/article_pics/default.jpg', null=True, upload_to='article_pics'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_cover',
            field=models.ImageField(blank=True, default='/quiz_pics/default.jpg', null=True, upload_to='quiz_pics'),
        ),
    ]
