# Generated by Django 4.0.10 on 2024-01-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_article_cover_quiz_quiz_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='welcome_page',
            field=models.TextField(default='Добро пожаловать на квиз по _____. Погрузитесь в захватывающий мир идей, вопросов и философских течений, которые формировали наше понимание мира и сущности бытия. В этом квизе вы пройдете через века мысли, от великих философов до ключевых философских концепций. Готовьтесь к увлекательному путешествию в мир философии и глубоких размышлений!', max_length=255, verbose_name='Quiz first page'),
        ),
    ]
